version: '3.3'

services:
  givEconomy-notification-service:
    #see https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref

    # is sometime you want to rollback you can change the tag manually in server( not commit to git)
    # from master to your desired commit hash and the run command:
    # 1. docker-compose -f docker-compose-staging.yml pull
    # 2. docker-compose -f docker-compose-staging.yml down
    # 3. docker-compose -f docker-compose-staging.yml up -d
    image: ghcr.io/giveth/giveconomy-notification-service:staging
    command: npm run start:docker:server
    environment:
      - NODE_ENV=staging
    restart: always
    env_file:
      - ./config/staging.env
