name: ci-staging

on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/giveth/giveconomy-notification-service:staging

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Redeploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST_ALL }}
          username: ${{ secrets.STAGING_USERNAME_ALL }}
          key: ${{ secrets.STAGING_PRIVATE_KEY_ALL }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd giveth-all
            docker-compose stop givEconomy-notification-service
            docker-compose pull givEconomy-notification-service
            docker-compose up -d givEconomy-notification-service
            docker image prune -a --force
